name: blackduck-hybrid-plugin
kind: workflow
apiVersion: automation.cloudbees.io/v1alpha1

on:
  push:
    branches:
      - blackduck-hybrid-plugin-test
  workflow_dispatch:

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write

jobs:
  blackduck-hybrid-scan:
    steps:
      - name: Checkout source code
        uses: cloudbees-io/checkout@v1
        with:
          ref: main

    #   - name: Save Docker image
    #     uses: docker://docker:24.0.7-cli  # ðŸ³ Docker CLI image
    #     run: |
    #      docker start docker pull node:18.15.0-alpine && docker save -o node.tar node:18.15.0-alpine

      - name: Run Black Duck hybrid scan
        uses: cloudbees-io/blackduck-sca-scan-dependency@apr
        with:
          ref: main
          server-url: https://blackduck.saas-qa.beescloud.com
          api-token: ${{ secrets.BD_API_TOKEN }}
          project-name: blackduckscan-Go-testing
          project-version: 0.0.1
          detect-cli-params: >-
            --detect.container.scan.file.path=public.ecr.aws/l7o7z1g8/actions/plugin-blackduck-sca:093c3ce91bfa01062b62922776d36900f83a7860
            --detect.tools=CONTAINER_SCAN
        